name: knitty
channels:
    - defaults
    - conda-forge
dependencies:
    - "python>=3.6"
    - "pip>=10.0.1"
    - "pandoc>=2.2.1"
    - jupyter_core
    - traitlets
    - ipython
    - jupyter_client
    - nbconvert
    - pandocfilters
    - py-pandoc
    - click
    - psutil
    - pyyaml
    - panflute

    - pytest
    - pytest-cov
    - sphinx
    - pandas
    - matplotlib
    - sphinx_rtd_theme
    - ghp-import

    - jupyter
    - notebook
    - bokeh
    - holoviews
    - altair

    - pip:
        - "git+https://github.com/kiwi0fruit/knitty"
